#!/bin/bash

len=-1

if test $# -gt 0; then
	if test $1 = -h; then
		echo "usage: $0 [length]"
		exit 0
	fi
	export len=$1
fi

while true; do
	if test $len -gt 0; then
		break
	fi
	echo -n "length of password: " >&2
	read len
done

./alnum < /dev/urandom | head -c $len
echo
